In [8]:
import numpy as np

# Create array from list
arr = np.array([1, 2, 3, 4, 5])

# Display array
print("Array:", arr)

# Print shape and datatype
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)

Array: [1 2 3 4 5]
Shape: (5,)
Data Type: int64


In [9]:
import numpy as np

# Create matrices
zeros_matrix = np.zeros((3, 4))
ones_matrix = np.ones((2, 5))

# Display matrices
print("Zeros Matrix:\n", zeros_matrix)
print("Shape:", zeros_matrix.shape)

print("\nOnes Matrix:\n", ones_matrix)
print("Shape:", ones_matrix.shape)

Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

Ones Matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


In [10]:
import numpy as np

# Create array
arr = np.arange(1, 13)

# Reshape
reshaped = arr.reshape(3, 4)

# Display
print("Original Array:", arr)
print("Shape:", arr.shape)

print("\nReshaped Array:\n", reshaped)
print("Shape:", reshaped.shape)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [11]:
import numpy as np

# Random integers
arr = np.random.randint(1, 100, 10)

print("Array:", arr)

print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))

Array: [82 30 32 73 72 51 58 38 75 41]
Minimum: 30
Maximum: 82
Mean: 55.2
Sum: 552


In [14]:
import pandas as pd

# Dictionary
data = {
    "Name": ["Aman", "Riya", "Rahul", "Sneha"],
    "Marks": [85, 90, 78, 92]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display
print(df)

# Data types
print("\nData Types:\n", df.dtypes)

    Name  Marks
0   Aman     85
1   Riya     90
2  Rahul     78
3  Sneha     92

Data Types:
 Name     object
Marks     int64
dtype: object


In [16]:
import pandas as pd
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
# First 5 records
print("First 5 rows:\n", df.head())

# Last 5 records
print("\nLast 5 rows:\n", df.tail())


First 5 rows:
    customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies      

In [17]:
# Info
print(df.info())

# Rows and columns
print("\nRows:", df.shape[0])
print("Columns:", df.shape[1])

# Missing values
print("\nMissing Values:\n", df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [18]:
summary = df.describe()

print(summary)

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000
